### ISSUE TITLE
how to "make"

### ISSUE THREAD

**Issue by odysseus90210** [jcolson/permanenttsb-csv-to-mint-csv#1]
Hi,

I'm sorry to bother you -- I’m a complete newbie with this. How do I compile/build/"make" this so that I can run it under Mac OS "Monterey"? Do I need to have Xcode installed?

Thanks!

**Comment by jcolson** [comment]
no worries.  If you install XCode and also install GoLang, you should be able to open the Terminal app and change directories to the source code directory and execute: `make`, which will make your current platform's binary.

I also just created a 'release' of the binaries (windows, linux and macos) which is available here:  

https://github.com/jcolson/convert-to-quicken-csv/releases/tag/v0.9.0

so you can download the binary without having to compile.

Cheers,
Jay

**Comment by odysseus90210** [comment]
Hi Jay,

Thanks!

I just downloaded the darwin universal version, but does it have to be installed in /bin?

—Marc

**Comment by odysseus90210** [comment]
Hi,

I gave the binary executable permissions and ran it with this string:

/Users/mbizer/Downloads/convert-to-quicken-csv-master/convert-to-quicken-csv-darwin-universal -type banktivity -input /Users/mbizer/Downloads/convert-to-quicken-csv-master/Export_00050688929_04072022_03012023.csv 

Apparently the binary panicked!

Date,Payee,FI Payee,Amount,CreditDebit,Category
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
main.banktivityCsvStuff({0x16b8f3ad6?, 0x0?})
	/Users/jcolson/src/personal/quickencsv/convert-to-quicken-csv.go:160 +0x84c
main.main()
	/Users/jcolson/src/personal/quickencsv/convert-to-quicken-csv.go:48 +0x1a4

Do you know why? My dates are in the form yyyy/mm/dd, if that helps.

**Comment by odysseus90210** [comment]
Whoops! Dates are in the form dd/mm/yyyy
